version: 0.2
env:
  secrets-manager:
    PUSHER_APP_KEY: 'PusherSecrets:key'
    PUSHER_APP_CLUSTER: 'PusherSecrets:cluster'
phases:
  install:
    runtime-versions:
      php: 7.4
      nodejs: 14
  build:
    commands:
      - composer install
      - npm install
      - npm run prod
artifacts:
  files:
    - 'app/**/*'
    - 'bootstrap/**/*'
    - 'config/**/*'
    - 'database/**/*'
    - 'public/**/*'
    - 'resources/**/*'
    - 'routes/**/*'
    - 'storage/**/*'
    - 'vendor/**/*'
